name: cv_app
description: CV application
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  app_base:
    path: ../app_base

  provider: ^6.0.5
  json_annotation: ^4.8.0
  google_fonts: ^4.0.3
  intl: ^0.18.0

  models:
    path: ../../models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3

flutter:
