name: iphone_desktop
description: iPhone desktop emulator
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  models:
    path: ./models

  cupertino_icons: ^1.0.2
  figma_squircle: 0.5.3
  intl: 0.18.0

  app_base:
    path: ./app_base

  linkedin_application:
    path: ./linkedin_application

  github_app:
    path: ./github_app

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/wallpapers/
    - assets/apps/