name: interactive_cv
description: iPhone-like interactive CV
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  models:
    path: ./models

  cupertino_icons: ^1.0.2
  figma_squircle: 0.5.3
  intl: 0.18.0
  provider: 6.0.5
  
  app_base:
    path: ./applications/app_base

  linkedin_application:
    path: ./applications/linkedin_application

  github_app:
    path: ./applications/github_app

  gmail:
    path: ./applications/gmail

  platform_utils:
    path: ./platform_utils

  window:
    path: ./window

  cv_app:
    path: ./applications/cv_app

  github_fidget:
    path: ./fidgets/github_fidget

  fast_noise: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.12.0

flutter:
  uses-material-design: true

  assets:
    - assets/wallpapers/
    - assets/apps/
    - assets/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#D2EADB"
    theme_color: "#D2EADB"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
