name: models
description: Models for iPhone entities
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  app_base:
    path: ../applications/app_base

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
